# Generated by Django 6.0.2 on 2026-04-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('id_number', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('overtime_pay', models.FloatField(blank=True, null=True)),
                ('allowance', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
