# Generated by Django 6.0.2 on 2026-05-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0003_account_employee_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="allowance",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="overtime_pay",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="deductions_health",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="deductions_tax",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="pag_ibig",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="sss",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="total_pay",
            field=models.FloatField(default=0),
        ),
    ]
